### PR TITLE
Export keepalive timeouts options to client code

### PR DESCRIPTION
**Pull request by chernikovdmitry**
Export keepalive timeouts options to client code
`Export keepalive timeouts options to client code`

> Export keepalive timeouts options to client code

### CODE REVIEW

**Review by angelskieglazki — APPROVED** [review]
Seems good!

**Review by kirill-scherba — CHANGES_REQUESTED** [review]
Extend with "disconnect timeout constant"

**Review by chernikovdmitry — COMMENTED** [review]
Now with disconnect timeouts and ping echo

**Review by chernikovdmitry — COMMENTED** [review]
fixed according to comments

**Review by a-vasiliev-wg — APPROVED** [review]
Good to go

**Review by a-vasiliev-wg — APPROVED** [review]
Good to go.

**Pull request merged**
